### ISSUE TITLE
Error launching w/ Python 3.8.5

### ISSUE THREAD

**Issue by ma-gh** [DL4L/Option-Payoff#1]
Hi, very interested in your project!

When I try to launch I receive the following:

Traceback (most recent call last):
  File "app.py", line 17, in <module>
    stock = Stock()
  File "/home/ma/gits/gh/Option-Payoff/Stock.py", line 41, in __init__
    self.tickers_select = [{"label": i, "value": i} for i in stock_info.tickers_dow(
  File "/home/ma/.envs/Option-Payoff/lib/python3.8/site-packages/yahoo_fin/stock_info.py", line 173, in tickers_dow
    table = pd.read_html(site)[0]
  File "/home/ma/.envs/Option-Payoff/lib/python3.8/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/ma/.envs/Option-Payoff/lib/python3.8/site-packages/pandas/io/html.py", line 1086, in read_html
    return _parse(
  File "/home/ma/.envs/Option-Payoff/lib/python3.8/site-packages/pandas/io/html.py", line 917, in _parse
    raise retained
  File "/home/ma/.envs/Option-Payoff/lib/python3.8/site-packages/pandas/io/html.py", line 898, in _parse
    tables = p.parse_tables()
  File "/home/ma/.envs/Option-Payoff/lib/python3.8/site-packages/pandas/io/html.py", line 217, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "/home/ma/.envs/Option-Payoff/lib/python3.8/site-packages/pandas/io/html.py", line 547, in _parse_tables
    raise ValueError("No tables found")
ValueError: No tables found

Python 3.8.5

-ma

**Comment by ma-gh** [comment]
Update:

I installed Python 3.7.0, created a venv, and ran the requirements list.

Same error:

> Traceback (most recent call last):
>   File "app.py", line 17, in <module>
>     stock = Stock()
>   File "/home/ma/gits/gh/Option-Payoff/Stock.py", line 41, in __init__
>     self.tickers_select = [{"label": i, "value": i} for i in stock_info.tickers_dow(
>   File "/home/ma/.envs/Option-Payoff/lib/python3.7/site-packages/yahoo_fin/stock_info.py", line 173, in tickers_dow
>     table = pd.read_html(site)[0]
>   File "/home/ma/.envs/Option-Payoff/lib/python3.7/site-packages/pandas/util/_decorators.py", line 296, in wrapper
>     return func(*args, **kwargs)
>   File "/home/ma/.envs/Option-Payoff/lib/python3.7/site-packages/pandas/io/html.py", line 1101, in read_html
>     displayed_only=displayed_only,
>   File "/home/ma/.envs/Option-Payoff/lib/python3.7/site-packages/pandas/io/html.py", line 917, in _parse
>     raise retained
>   File "/home/ma/.envs/Option-Payoff/lib/python3.7/site-packages/pandas/io/html.py", line 898, in _parse
>     tables = p.parse_tables()
>   File "/home/ma/.envs/Option-Payoff/lib/python3.7/site-packages/pandas/io/html.py", line 217, in parse_tables
>     tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
>   File "/home/ma/.envs/Option-Payoff/lib/python3.7/site-packages/pandas/io/html.py", line 547, in _parse_tables
>     raise ValueError("No tables found")
> ValueError: No tables found
>

**Comment by a5m0** [comment]
You just need to update yahoo-fi

pip install yahoo-fi --upgrade
